"""init base tables

Revision ID: ea5e8fc2ea5b
Revises:
Create Date: 2026-04-26 12:15:15.615050

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea5e8fc2ea5b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "hugs_given", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "hugs_receive", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "warns_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "marriage_score", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("married_to_id", sa.Integer(), nullable=True),
        sa.Column("married_at", sa.DateTime(), nullable=True),
        sa.Column("pending_proposal_to_id", sa.Integer(), nullable=True),
        sa.Column(
            "joined_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_activity",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["married_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pending_proposal_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "group_id", name="uq_user_group"),
    )
    op.create_index(
        op.f("ix_memberships_group_id"), "memberships", ["group_id"], unique=False
    )
    op.execute(
        "INSERT INTO users (id, telegram_id, username, first_name, created_at, updated_at) "
        "VALUES (99, 0, 'BOT_USERNAME', 'BOT_FIRSTNAME', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memberships_group_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
